### ISSUE TITLE
One of Undynes green attacks seems broken?

### ISSUE THREAD

**Issue by Vultumast** [Vultumast/UndertaleDecomp#3]
One of her attacks just, leave you there for a bit???

**Comment by zyledev** [comment]
genocide, neutral, or pacifist?

**Comment by danielah05** [comment]
in genocide at least, the spear patterns get set through an object called "obj_spearblocker", after running the game through a debugger, it looks like lesson "-12" in the user event 1 is the one that has the big pause

**Comment by Vultumast** [comment]
![image](https://github.com/Vultumast/UndertaleDecomp/assets/152120810/4b614a15-00b1-4cab-b41d-ad43c41ab1f0)
Appears to be an issue here, going to look into it later tonight.

**Comment by Vultumast** [comment]
Fixed as of commit 809bdc9
