### ISSUE TITLE
Slopes have extremely weird behavior? Might be a result of broken GMS 2 built in collisions.

### ISSUE THREAD

**Issue by Vultumast** [Vultumast/UndertaleDecomp#6]
https://github.com/Vultumast/UndertaleDecomp/assets/152120810/bd136354-ebb6-482f-bbd5-083492b8a1b5

**Comment by Vultumast** [comment]
I really think is a bug in the runtime

**Comment by zyledev** [comment]
yyg reworked collisions a while ago so yeah this is most likely the case.

**Comment by danielah05** [comment]
from what we tested the collisions worked fine when running the game in debug mode (gms2 one, not the undertale global.debug)? but not when the game is run normally, so i guess we just gotta wait for yoyo to fix it

**Comment by zyledev** [comment]
> so i guess we just gotta wait for yoyo to fix it

yoyo isnt going to fix this I believe, theres an option in GMS2 which enables compatibility collisions and that will most likely fix this issue.

**Comment by danielah05** [comment]
> > so i guess we just gotta wait for yoyo to fix it
> 
> yoyo isnt going to fix this I believe, theres an option in GMS2 which enables compatibility collisions and that will most likely fix this issue.

i think we had compatibility collisions on at some point (might be wrong tho? id need to test it again) and it didnt seem to fix it but i could be wrong

**Comment by Vultumast** [comment]
We've tested compatible collisions on and off and the issue still persists
